name: Vial Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: qmk/qmk_firmware@main
      with:
        command: compile
        keyboard: kbdcraft/israfel
        keymap: vial
